image: cirrusci/flutter

before_script:
  - flutter pub get

stages:
  - analyze-and-test
  - documentation

analyze-and-test:
  stage: analyze-and-test
  script:
#    - flutter analyze
    - flutter test --coverage


documentation:
  stage: documentation
  script:
    - dartdoc