image: cirrusci/flutter:2.0.1

before_script:
  - flutter pub get

stages:
#  - test
  - analyze

test:
  stage: test
  script:
    - flutter test

analyze:
  stage: analyze
  script:
    - flutter analyze
