image: cirrusci/flutter

before_script:
  - flutter pub get

stages:
  - test
  - analyze

test:
  stage: test
  script:
    - flutter test --coverage

analyze:
  stage: analyze
  script:
    - flutter analyze
